### ISSUE TITLE
Unable to register parser with previously configured RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();

### ISSUE THREAD

**Issue by vasylholovchak93** [rest-assured/rest-assured#684] opened 2016-04-25 15:47 UTC
This code 
```
public class RestAssuredExampleTest {
    @BeforeClass
    public void initializeRestAssured() {
        RestAssured.baseURI = "http://192.168.99.100";
        RestAssured.port = 8082;
        RestAssured.basePath = "rest-assured-example/service";
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    @Test
    public void testRegisterParserForUnknownContentType() {
        RestAssured.registerParser("text/json", Parser.JSON);
        when().get("/detail/json").then().body("test", equalTo(true));
    }
}
```
throws
>  java.lang.IllegalStateException: Expected response body to be verified as JSON, HTML or XML but content-type 'text/json' is not supported out of the box.
Try registering a custom parser using:
   RestAssured.registerParser("text/json", <parser type>);

While code
```
public class RestAssuredExampleTest {
    @BeforeClass
    public void initializeRestAssured() {
        RestAssured.baseURI = "http://192.168.99.100";
        RestAssured.port = 8082;
        RestAssured.basePath = "rest-assured-example/service";
    }

    @Test
    public void testRegisterParserForUnknownContentType() {
        RestAssured.registerParser("text/json", Parser.JSON);
        when().get("/detail/json").then().body("test", equalTo(true));
    }
}
```
works without any issues.

The difference is only in setting RestAssured.enableLoggingOfRequestAndResponseIfValidationFails(); in @BeforeClass.

**Comment by johanhaleby** [comment] 2016-04-26 06:02
Looks like a bug indeed, thanks for reporting.

**Comment by johanhaleby** [comment] 2016-05-21 08:28
I cannot seem to reproduce this.

My test looks like this:

```java
RestAssured.baseURI = "http://127.0.0.1";
                RestAssured.port = 8080;
                RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
                RestAssured.registerParser("application/json", Parser.JSON);
                when().get("/lotto").then().log().all().body("lotto.lottoId", is(5));
```

and it works. What version of REST Assured are you using?

**Comment by vasylholovchak93** [comment] 2016-05-21 08:48
2.9.0

**Comment by johanhaleby** [comment] 2016-05-21 09:05
Can you provide some more info? What does the response log say if you do:

```java
when().get("/detail/json").then().log().all().body("test", equalTo(true));
```

**Comment by vasylholovchak93** [comment] 2016-05-21 10:57
Here is whole log:
```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: text/json
Transfer-Encoding: chunked
Date: Sat, 21 May 2016 10:45:36 GMT

{"test":true}
Request method:	GET
Request path:	http://192.168.99.100:8080/rest-assured-example/service/detail/json
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Multiparts:		<none>
Headers:		Accept=*/*
Cookies:		<none>
Body:			<none>

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: text/json
Transfer-Encoding: chunked
Date: Sat, 21 May 2016 10:45:36 GMT

{
    "test": true
}
```
And the whole stactrace:
```
java.lang.IllegalStateException: Expected response body to be verified as JSON, HTML or XML but content-type 'text/json' is not supported out of the box.
Try registering a custom parser using:
   RestAssured.registerParser("text/json", <parser type>);
Content was:
{"test":true}


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.jayway.restassured.assertion.StreamVerifier.newAssertion(StreamVerifier.groovy:48)
	at com.jayway.restassured.assertion.StreamVerifier$newAssertion.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at com.jayway.restassured.assertion.BodyMatcher.validate(BodyMatcher.groovy:85)
	at com.jayway.restassured.assertion.BodyMatcher$validate$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at com.jayway.restassured.assertion.BodyMatcherGroup$_validate_closure2.doCall(BodyMatcherGroup.groovy:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3170)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3140)
	at org.codehaus.groovy.runtime.dgm$66.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.jayway.restassured.assertion.BodyMatcherGroup.validate(BodyMatcherGroup.groovy:47)
	at com.jayway.restassured.assertion.BodyMatcherGroup$validate$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:585)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:760)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.content(ResponseSpecificationImpl.groovy:251)
	at com.jayway.restassured.specification.ResponseSpecification$content$2.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:234)
	at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:264)
	at rest.RestAssuredExampleTest.testRegisterParserForUnknownContentType(RestAssuredExampleTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
And the code which was executed:
```
    @Test
    public void testRegisterParserForUnknownContentType() {
        RestAssured.baseURI = "http://192.168.99.100";
        RestAssured.port = 8080;
        RestAssured.basePath = "rest-assured-example/service";
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.registerParser("text/json", Parser.JSON);
        when().get("/detail/json").then().log().all().body("test", equalTo(true));
    }
```

**Comment by johanhaleby** [comment] 2016-05-21 11:45
The problem had to do with "text/json". You shouldn't need to register the text/json parser at all. I've now deployed a new snapshot that should address this issue. Please try version `3.0.0-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

The groupId has changed in the next version of REST Assured so you should depend on this artefact:

<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>3.0.0-SNAPSHOT</version>
</dependency>

I'll close the issue for now. Reopen if there's still a problem. 

Thanks for your help!

**Closed by johanhaleby** 2016-05-21 11:45 UTC

**Comment by jamesvanhorn** [comment] 2017-10-09 15:19
Came across this issue while trying to debug the same issue. As soon as I comment out the filters or enableLoggingOfRequestAndResponseIfValidationFails line, the tests work fine.

Note that I am setting the parser for "text/plain" and not "text/json".

Using rest-assured 3.0.2

```
RestAssured.filters(new RequestLoggingFilter(), new ResponseLoggingFilter()); // Or RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
RestAssured.registerParser("text/plain", Parser.JSON);
RestAssured.defaultParser = Parser.JSON;

given().when().get(this.URI); //Response of Content-Type: text/plain but need to parse as  JSON
```

**Comment by techbecca** [comment] 2017-11-14 13:09
I have the same issue as jamesvanhorn, setting a parser for "text/plain". Thing is, if I don't do the call `RestAssured.registerParser("text/plain", Parser.JSON);` , I get IllegalStateException when I try to do `then().contenttype(ContentType.TEXT)` on my responses and get prompted to register it as a custom parser.

**Comment by rkraneis** [comment] 2021-12-08 10:45
Same problem here with RestAssured 4.4.0; as soon as `RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();` is active, `RestAssured.registerParser(...);` is ignored.

**Comment by MHipo** [comment] 2024-06-25 09:47
I have a similar problem when using RestAssured:

```RestAssured.given()
                .contentType("application/json")
                .body(entityRequest)
                .when()
                .post("/api/myApi")
                .then()
                .log().all()
                .statusCode(201)
                .body("id", Matchers.notNullValue())
                .body("name", Matchers.equalTo(entityRequest.name()))
                .body("description", Matchers.equalTo(entityRequest.description()))
                .body("price", Matchers.is(entityRequest.price().intValueExact()));
    }
```
with the following maven dependency:

```
<dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>5.4.0</version>
        </dependency>
```I got the following error:

```
java.lang.IllegalStateException: Expected response body to be verified as JSON, HTML or XML but no content-type was defined in the response.
Try registering a default parser using:
   RestAssured.defaultParser(<parser type>);
Content was:

```
I did add the RestAssured.defaultParser...but it did not work. Any help will greatly be appreciated.

**Comment by rcbandit111** [comment] 2025-04-13 21:14
I have the same issue with 5.5.1. Can you advise some solution?
