### ISSUE TITLE
How to troubleshoot a GET request that is not working with RA but works well with Postman

### ISSUE THREAD

**Issue by ashekhar** [rest-assured/rest-assured#749] opened 2016-10-04 17:21 UTC
I have a simple GET request that is working well with Postman client. However same request is not working at all with REST-Assured.  Any trouble shooting tips that I can follow/look at?

![image](https://cloud.githubusercontent.com/assets/3721319/19084609/2149fd54-8a1c-11e6-84f3-dbbd07ba124c.png)
![image](https://cloud.githubusercontent.com/assets/3721319/19084632/354941ca-8a1c-11e6-8a59-628e9fc03a53.png)

Is there a trouble shooting blog/page with suggestions/tips?

Thanks 
Anil

**Comment by klubi** [comment] 2016-10-04 18:44
I'll extend this question a bit...
I have the same problem with POST request and basic + preemptive authorization.
For some reason Postman and curl work just fine, but RA does not...

**Comment by ashekhar** [comment] 2016-10-04 20:50
Seeing your post, I tried using cURL ... it worked just fine ... but not with RA ...

**Comment by johanhaleby** [comment] 2016-10-05 05:54
@ashekhar What if you try to remove the charset? See https://github.com/rest-assured/rest-assured/wiki/Usage#avoid-adding-the-charset-to-content-type-header-automatically

**Comment by klubi** [comment] 2016-10-05 10:58
@ashekhar yeah, so we have the same issue
@johanhaleby I did try that, unfortunately did not help :/

**Comment by johanhaleby** [comment] 2016-10-05 11:03
What if you use wireshark? If you could share what the request made by REST Assured looks like and what Postman looks like we could probably figure out what's wrong.

**Comment by klubi** [comment] 2016-10-05 12:45
@johanhaleby to be honest I hate that tool, I wasn't able to make it display info I needed... ever...

**Comment by johanhaleby** [comment] 2016-10-05 13:08
Just find the request and select "Follow TCP Stream" and you'll be able to see the request and response in a new window.

**Comment by klubi** [comment] 2016-10-05 13:41
yeah... the problem is to find the right one...

**Comment by ashekhar** [comment] 2016-10-05 18:02
@johanhaleby @klubi 
Here is the comparision of the HTTP stream between the one I see from cURL and RA. With RA nothing is returned back.
![image](https://cloud.githubusercontent.com/assets/3721319/19125250/2f550d2e-8aeb-11e6-82e6-c797db2b4f9a.png)
![image](https://cloud.githubusercontent.com/assets/3721319/19125260/376a54ec-8aeb-11e6-9ad6-e1c9241e2494.png)

**Comment by ashekhar** [comment] 2016-10-05 20:05
Request method:	GET
Request URI:	http://aic-srvfab-dev1.westus.cloudapp.azure.com:8695/api/clm/v1/agreements
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Multiparts:	<none>
Headers:		tenant_id=4
			uid=787703BB-6F5B-E611-80DE-C4346BB59884
			Accept=application/json, text/plain, */*
			destination_app=CLM
Cookies:		<none>
Body:		<none>
![image](https://cloud.githubusercontent.com/assets/3721319/19129294/af0c1c00-8afb-11e6-9640-068b1ad43ea8.png)

**Comment by ashekhar** [comment] 2016-10-05 21:22
When I tried to add 2 headers to see if that would of any help ... But I got error ... and these 2 are not shown as being added to the list of headers ... 

Referer: http://aic-clm-dev-ui1.apttuscloud.io/CLM/
Origin: http://aic-clm-dev-ui1.apttuscloud.io

**Code:**

`package` apttus.qa.scratchpad;

import static io.restassured.RestAssured.given;

import java.util.HashMap;

import org.apache.http.HttpStatus;

import apttus.qa.api.azure.common.GAPI_CommonHelperMethods;

import io.restassured.http.Header;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import io.restassured.config.EncoderConfig;
import io.restassured.config.RestAssuredConfig;

public class TestRESTAPI {

	public static String serviceFabricHost				= "aic-srvfab-dev1.westus.cloudapp.azure.com:8695";
	public static String serviceFabricURL				= "http://" + serviceFabricHost;

	public static String baseURI_ServiceFabric			= "http://aic-srvfab-dev1.westus.cloudapp.azure.com:8695/";
	public static String baseURI						= baseURI_ServiceFabric;

	public static String header_UID_KeyQA				= "uid";
	public static String header_UID_ValueQA				= "787703BB-6F5B-E611-80DE-C4346BB59884";
	
	public static String header_TenantId_KeyQA			= "tenant_id";
	public static String header_TenantId_ValueQA		= "4";
	
	public static String header_destinationApp_KeyQA	= "destination_app";
	public static String header_destinationApp_ValueQA	= "CLM";

	public static String header_Host_KeyQA				= "Host";
	public static String header_Host_ValueQA			= "aic-srvfab-dev1.westus.cloudapp.azure.com:8695";
	
	public static String header_Referer_KeyQA			= "Referer";
	public static String header_Referer_ValueQA			= "http://aic-clm-dev-ui1.apttuscloud.io/CLM/";
	
	public static String header_Origin_KeyQA			= "Origin";
	public static String header_Origin_ValueQA			= "http://aic-clm-dev-ui1.apttuscloud.io";
	
	public static String header_Accept_KeyQA			= "Accept";
	public static String header_Accept_ValueQA			= "application/json, text/plain, */*";
		
	public static HashMap<String, String> headerValues	= new HashMap<String, String>();
	
	public static void get(String url) {
		
    	System.out.println("	DEBUG (Info): " + GAPI_CommonHelperMethods.getCurrentMethodName() + " ...");
    	System.out.println("		DEBUG (Info): url " + url);

		Response resp = given()
				.headers(headerValues)
				.log().everything()
			.expect()
				.log().all()
				.statusCode(HttpStatus.SC_OK)
			.when()
				.get(url);

		GAPI_CommonHelperMethods.dumpResponse_Raw(resp);
	}

	
	public static void main(String[] args) {

	    System.out.println("	DEBUG (INFO): baseURI: " + baseURI);
		System.out.println("	DEBUG (INFO): header_UID_KeyQA:              " + header_UID_KeyQA);
		System.out.println("	DEBUG (INFO): header_UID_ValueQA:            " + header_UID_ValueQA);
		headerValues.put(header_UID_KeyQA, header_UID_ValueQA);
		
   	    System.out.println("	DEBUG (INFO): header_TenantId_KeyQA:         " + header_TenantId_KeyQA);
   	    System.out.println("	DEBUG (INFO): header_TenantId_ValueQA:       " + header_TenantId_ValueQA);
   		headerValues.put(header_TenantId_KeyQA, header_TenantId_ValueQA);
   		
   	    System.out.println("	DEBUG (INFO): header_destinationApp_KeyQA:   " + header_destinationApp_KeyQA);
   	    System.out.println("	DEBUG (INFO): header_destinationApp_ValueQA: " + header_destinationApp_ValueQA);
   		headerValues.put(header_destinationApp_KeyQA, header_destinationApp_ValueQA);
   		
   	    System.out.println("	DEBUG (INFO): header_Referer_KeyQA:          " + header_Referer_KeyQA);
   	    System.out.println("	DEBUG (INFO): header_Referer_ValueQA:        " + header_Referer_ValueQA);
   		headerValues.put(header_Host_KeyQA, header_Referer_ValueQA);
   		
   	    System.out.println("	DEBUG (INFO): header_Origin_KeyQA:           " + header_Origin_KeyQA);
   	    System.out.println("	DEBUG (INFO): header_Origin_ValueQA:         " + header_Origin_ValueQA);
   		headerValues.put(header_Host_KeyQA, header_Origin_ValueQA);

   		String url = serviceFabricURL + "/api/clm/v1/agreements";
   		
   		get(url);
	}
}
`

Console Output:

`	DEBUG (INFO): baseURI: http://aic-srvfab-dev1.westus.cloudapp.azure.com:8695/
	DEBUG (INFO): header_UID_KeyQA:              uid
	DEBUG (INFO): header_UID_ValueQA:            787703BB-6F5B-E611-80DE-C4346BB59884
	DEBUG (INFO): header_TenantId_KeyQA:         tenant_id
	DEBUG (INFO): header_TenantId_ValueQA:       4
	DEBUG (INFO): header_destinationApp_KeyQA:   destination_app
	DEBUG (INFO): header_destinationApp_ValueQA: CLM
	DEBUG (INFO): header_Referer_KeyQA:          Referer
	DEBUG (INFO): header_Referer_ValueQA:        http://aic-clm-dev-ui1.apttuscloud.io/CLM/
	DEBUG (INFO): header_Origin_KeyQA:           Origin
	DEBUG (INFO): header_Origin_ValueQA:         http://aic-clm-dev-ui1.apttuscloud.io
	DEBUG (Info): apttus.qa.scratchpad.TestRESTAPI.get() ...
		DEBUG (Info): url http://aic-srvfab-dev1.westus.cloudapp.azure.com:8695/api/clm/v1/agreements
Request method:	GET
Request URI:		http://aic-srvfab-dev1.westus.cloudapp.azure.com:8695/api/clm/v1/agreements
Proxy:			<none>
Request params:	<none>
Query params:		<none>
Form params:		<none>
Path params:		<none>
Multiparts:		<none>
Headers:			tenant_id=4
				uid=787703BB-6F5B-E611-80DE-C4346BB59884
				destination_app=CLM
				Host=http://aic-clm-dev-ui1.apttuscloud.io
				Accept=*/*
Cookies:			<none>
Body:			<none>

HTTP/1.1 400 Bad Request
Content-Type: text/html; charset=us-ascii
Server: Microsoft-HTTPAPI/2.0
Date: Wed, 05 Oct 2016 20:18:11 GMT
Connection: close
Content-Length: 334

<html>
  <head>
    <title>Bad Request</title>
    <meta http-equiv="Content-Type" content="text/html; charset=us-ascii"/>
  </head>
  <body>
    <h2>Bad Request - Invalid Hostname</h2>
    <hr/>
    <p>HTTP Error 400. The request hostname is invalid.</p>
  </body>
</html>`

**Comment by johanhaleby** [comment] 2016-10-06 05:18
Isn't this because you need to do some form of authentication? I've never used Azure but a quick Google search gives me this: https://azure.microsoft.com/en-us/documentation/articles/service-fabric-cluster-security/. Could it be that you've already authenticated in the browser and Postman is able to reuse what's already in the browser?

**Comment by ashekhar** [comment] 2016-10-06 16:57
@johanhaleby True. But here we have not enabled any authentication for now. Just need to send 3 header values and that's it.

**Comment by Lambeaux** [comment] 2017-06-06 19:35
Seem like this is more of an Azure problem, and not Rest Assured. +1 to close.

**Comment by johanhaleby** [comment] 2017-06-07 04:48
I'm closing, please point out if you feel that this is the wrong decision.

**Closed by johanhaleby** 2017-06-07 04:48 UTC
